version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "FleetMgmnt"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-al2i1rsjaeze"
s3_prefix = "FleetMgmnt"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

